FROM node:20.2.0

WORKDIR /app/

COPY ./package*.json ./
COPY ./src/ ./src/
COPY ./astro.config.mjs ./
COPY ./tsconfig.json ./

RUN npm install -g npm@9.8.1 && \
	npm cache clean --force && \
	npm ci && \
	npm run build

EXPOSE 4001

CMD node ./dist/server/entry.mjs
